### ISSUE TITLE
Cant hide menu after it collapse

### ISSUE THREAD

**Issue by jonathanRoque07** [glhd/wp-bootstrap-widgets#5]
am i doing wrong? widgets not showing but i design my navbar with bootstrap and use your plugins because before my index is working but on other page it isn't but after adding your plugin it is now working in all pages but menu is not hiding. i didnt write anything in functions. just in header the wp_nav_menu and some classes.

edit: i think theres a conflict on default theme even though i erase all of it. so i created a new theme and paste all of my work from the default theme i used. But in the index.php the navbar is not again working. im new to wordpress and i cant find an answer online. thank you

**Comment by jgrossi** [comment]
Hey @jonathanRoque07 the goal of the plugin is to provide an easy way to include Bootstrap components inside WordPress using widgets. The plugin has no conflict with others menus you have in your application. 

To use a widget using this plugin you might add one in a sidebar or in a page using the [Page Builder](https://wordpress.org/plugins/siteorigin-panels/) plugin (another one). Once this plugin creates widgets there's no conflict with themes since you have to include each widget you want to use. 

Any question just ask. And thanks for using the plugin.
